name: Fast-forward

on:
  pull_request:
    types: [labeled]

permissions: write-all

jobs:
  fast_forward:
    name: Fast-forward
    runs-on: ubuntu-latest
    if: github.event.label.name == 'fast-forward'

    steps:
      - name: print
        run: echo ${{ github.base_ref }} <- ${{ github.head_ref }}

      - name: Checkout pull request
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Fast-forward & push
        env:
          PR_COMMIT: ${{ github.event.pull_request.head.sha }}
        run: |
          git checkout ${{ github.base_ref }}
          git merge --ff-only "$PR_COMMIT"
          git push origin ${{ github.base_ref }}
